### PR TITLE
DISCOVERYACCESS-8183: remove popover for author info button; change t…

### PR DESCRIPTION
**Pull request by mhk33**
…o  link only. This is because the popover is not keyboard accessible. Bootstrap recommends using a different element for displaying complex content, including links.

### CODE REVIEW

**Comment by chrisrlc** [comment]
Also! I believe there are tests to remove as well.

**Comment by mhk33** [comment]
@chrisrlc Ah okay. I wasn't sure if we want to leave any of that code for repurposing later. But we can always put it back I guess! Also I'm not sure how much any of this code overlaps with LD4P work/code.

**Comment by chrisrlc** [comment]
All of it comes from ld4p work! But we have version control, so if it's no longer being used, and we have no known plans for it being used in the future, we should probably clean it out of our repo.

When I was sending you those links, I also realized how strange it was that the Author info button is rendered by the html, but the Work info button is generated by the javascript. That'd be nice to make more consistent!

**Comment by mhk33** [comment]
Yeah I saw that with the work info. Do we need js to render it? The author info button seems much more simple/less code.

**Comment by chrisrlc** [comment]
I believe all the logic that determines if the Work info button should display exists at rails render time, so I think we can just render the Work info button in the rails views, same as we're doing it for Author info.

The button html is fairly similar for Author info vs Work info - the latter just needs to be moved into a rails view. Just: https://github.com/cul-it/blacklight-cornell/blob/dev/app/views/catalog/_show_default.html.erb#L24 vs https://github.com/cul-it/blacklight-cornell/blob/dev/app/assets/javascripts/linked_data/work.js#L151. I suppose we can also simplify some of those html attributes on the Work info button if it won't trigger a popover anymore (no more tabindex or data-trigger?). We could also add matomo tracking to the Work info button too if you think that's useful?

**Comment by chrisrlc** [comment]
Possibly we don't want to add html to the rails views in exactly the same way as the Author info button actually, since it seems like a more blacklight-y way to customize solr field display is to set a helper method in the CatalogController (https://github.com/cul-it/blacklight-cornell/blob/dev/app/controllers/catalog_controller.rb#L317), rather than adding extra logic to app/views/_show_default.html.erb. Would need to dig into that code a bit more to know for sure.

**Comment by mhk33** [comment]
@chrisrlc OK, I did some stuff: https://github.com/cul-it/blacklight-cornell/commit/284dba417368e38dc1490f107671589f14f01655

Not sure I got it all right.

I did not, however, add the Work link back as mentioned in previous comments; would need help with this one if you don't mind taking a look --
https://github.com/cul-it/blacklight-cornell/pull/2050#issuecomment-1796122357

Also tests may still need to be updated, but was waiting on adding back the Work info button. So as we stand now, the Author info button works as it had for mobile and the Work button is not appearing.

**Pull request closed without merging**
